name: flutter_file_manager_android
description: Android platform implementation of flutter_file_manager.
version: 1.1.0
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/flutter_file_manager_android

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_platform_interface: ^1.1.0
  mime: ^1.0.2
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.maniak.flutter_file_manager_android
        pluginClass: FlutterFileManagerAndroidPlugin
