name: flutter_file_saver
description: Interface to provide a way to save files on the device in Flutter.
version: 0.5.1
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/flutter_file_saver

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_android: ^1.1.1
  flutter_file_manager_ios: ^1.1.0
  flutter_file_manager_macos: ^1.1.0
  flutter_file_manager_platform_interface: ^1.1.0
  flutter_file_manager_web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_file_manager_android
      ios:
        default_package: flutter_file_manager_ios
      web:
        default_package: flutter_file_manager_web
      macos:
        default_package: flutter_file_manager_macos
