name: flutter_file_saver
description: Interface to provide a way to save files on the device in Flutter.
version: 0.1.0
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/flutter_file_saver

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_platform_interface: ^1.0.1
  flutter_file_manager_web: ^1.0.1
  path_provider: ^2.0.10
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: flutter_file_manager_web
