name: flutter_file_manager_platform_interface
description: A common platform interface for the flutter_file_manager plugin.
version: 1.0.0
homepage: https://github.com/TesteurManiak/flutter_file_manager
repository: https://github.com/TesteurManiak/flutter_file_manager/tree/main/flutter_file_manager_platform_interface

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: