name: flutter_file_manager_web
description: Web platform implementation of flutter_file_saver.
version: 1.1.0
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/flutter_file_manager_web

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_platform_interface: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  mime: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFileManagerWeb
        fileName: flutter_file_manager_web.dart
