name: flutter_file_saver
description: Interface to provide a way to save files on the device in Flutter.
version: 0.6.2
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/packages/flutter_file_saver
issue_tracker: https://github.com/TesteurManiak/flutter_file_saver/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_android: ^1.2.1
  flutter_file_manager_ios: ^1.1.1
  flutter_file_manager_macos: ^1.1.1
  flutter_file_manager_platform_interface: ^1.1.1
  flutter_file_manager_web: ^1.1.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_file_manager_android
      ios:
        default_package: flutter_file_manager_ios
      web:
        default_package: flutter_file_manager_web
      macos:
        default_package: flutter_file_manager_macos
