name: flutter_file_manager_web
description: Web platform implementation of flutter_file_manager.
version: 1.0.1
homepage: https://github.com/TesteurManiak/flutter_file_manager
repository: https://github.com/TesteurManiak/flutter_file_manager/tree/main/flutter_file_manager_web

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_platform_interface: ^1.0.1
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFileManagerWeb
        fileName: flutter_file_manager_web.dart
