name: flutter_file_manager_platform_interface
description: A common platform interface for the flutter_file_manager plugin.
version: 1.1.1
homepage: https://github.com/TesteurManiak/flutter_file_saver
repository: https://github.com/TesteurManiak/flutter_file_saver/tree/main/packages/flutter_file_manager_platform_interface
issue_tracker: https://github.com/TesteurManiak/flutter_file_saver/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  lints: ^3.0.0
