name: flutter_file_manager_macos
description: MacOS platform implementation of flutter_file_saver.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_file_manager_platform_interface: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      macos:
        pluginClass: FlutterFileManagerMacosPlugin
