name: tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: subosito/flutter-action@v2.14.0
      - uses: bluefireteam/melos-action@v3
      - name: Analyze package
        run: melos analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: subosito/flutter-action@v2.14.0
      - uses: bluefireteam/melos-action@v3
      - name: Run tests
        run: melos test
