name: tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.4.0
      - uses: bluefireteam/melos-action@v2
      - name: Analyze package
        run: melos run analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.4.0
      - uses: bluefireteam/melos-action@v2
      - name: Run tests
        run: melos run test
